fos_ck_editor:
    default_config: ckeditor_full
    configs:
        ckeditor_full:
            toolbar: ckeditor_full
            extraPlugins:
                - 'media'
    plugins:
        media:
            path: '/bundles/bitbagsyliuscmsplugin/js/ckeditor-plugins/media/'
            filename: 'plugin.js'
    toolbars:
        configs:
            ckeditor_full:
                - '@full.document'
                - '@full.clipboard'
                - '@full.editing'
                - '@full.forms'
                - '/'
                - '@full.basic_styles'
                - '@full.paragraph'
                - '@full.links'
                - '@full.insert'
                - '/'
                - '@full.styles'
                - '@full.colors'
                - '@full.tools'
                - '@full.about'
