fos_ck_editor:
    default_config: bitbag_sylius_cms_plugin
    configs:
        bitbag_sylius_cms_plugin:
            toolbar: bitbag_sylius_cms_plugin
            extraPlugins:
                - 'media'
    plugins:
        media:
            path: '/bundles/bitbagsyliuscmsplugin/js/ckeditor-plugins/media/'
            filename: 'plugin.js'
    toolbars:
        configs:
            bitbag_sylius_cms_plugin:
                - '@full.document'
                - '@full.clipboard'
                - '@full.editing'
                - '@full.forms'
                - '/'
                - '@full.basic_styles'
                - '@full.paragraph'
                - '@full.links'
                - '@full.insert'
                - '/'
                - '@full.styles'
                - '@full.colors'
                - '@full.tools'
                - '@full.about'
