bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"
app_admin_course:
    resource: |
        alias: app.course
        section: admin
        path: /admin/app/course
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_course
        vars:
            all:
                subheader: app.ui.course
            index:
                icon: 'book'
    type: sylius.resource
app_admin_course_page:
    resource: |
        alias: app.course_page
        section: admin
        path: /admin/app/course_page
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_course_page
        vars:
            all:
                subheader: app.ui.course_page
            index:
                icon: 'book'
    type: sylius.resource
sylius_shop_account_courses:
    path: /{_locale}/account/courses
    methods: [GET]
    defaults:
        _controller: App\Controller\CourseController:listAction
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
sylius_shop_account_course:
    path: /{_locale}/account/courses/{slug}
    methods: [GET]
    defaults:
        _controller: App\Controller\CourseController:courseAction
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
sylius_shop_account_course_page:
    path: /{_locale}/account/courses/{slug}/{pageSlug}
    methods: [GET]
    defaults:
        _controller: App\Controller\CourseController:coursePageAction
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"